### ISSUE TITLE
Monster Class

### ISSUE THREAD

**Issue by lwatson98** [Azurekuz/RPG-Task-Manager#54] opened 2020-03-27 15:04 UTC
How to Demo:
The player should enter a dungeoun and within the CombatUI be prompt to attack this class
Estimate: 2hr

Assignee:TBD

Time worked on card: 2min

**Comment by E-3P0** [comment] 2020-04-06 17:48
Closing - duplicate of enemy card

**Closed as completed by E-3P0** 2020-04-06 17:48 UTC
Labels: duplicate
